name: 书旗小说
on:
  workflow_dispatch:
  schedule:
     - cron: '0 0-20/1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      
      - name: Checkout
        run: |
          git clone https://github.com/66903202/ziye.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/js
          npm install got
          npm install cron
          npm install request
      - name: '【书旗小说】'
        run: |
          cd ~/js   
          node Task/shuqi.js
        env:

          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
